### ISSUE TITLE
Implement step for sending discord message about successful deployment to environment

### ISSUE THREAD

**Issue by mkjmdski** [vegaprotocol/jenkins-shared-library#104]
Could be send only on tickbox. A lot of requests about deployment include informing community about successful deployment, why not do it from jenkins?

**Comment by jeremyletang** [comment]
The only reason I could think of for not doing that is that sometime it takes a couple of tries to get the new testnet environment completely right, and that could be multiple restarts which would kinda spam the discord or whatever. Is that a real issue though, not so sure.
