### ISSUE TITLE
Improve capsule system-tests pipeline

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/jenkins-shared-library#125]
A couple of things are missing in that pipeline.
Let's add them:
- [x] global timeout on the whole job,
- [x] timestamps to every logline,
- [x] delete historical builds, verify with the QA team if 14 or 30 days is good,
- [x] add a `timeout` argument to the helper function called from other pipelines and use it as a global timeout.

If time permits
- [x] investigate how to improve log extraction from vegacapsule for vega/data-node services.

**Comment by gordsport** [comment]
for vegacapsule logs see:
- https://github.com/vegaprotocol/vegacapsule/pull/217
