### ISSUE TITLE
Move vega-market-sim Jenkinsfile steps into shared library

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/jenkins-shared-library#195]
We would like to be able to run Vega [market-sim](https://github.com/vegaprotocol/vega-market-sim) tests as part of PRs from the main Vega repository to identify breaking changes early. As part of this, we need to move the configuration from the Jenkinsfile within Vega-market-sim into a shared location to be used in Vega too.

**Comment by gordsport** [comment]
this has been implemented
