### ISSUE TITLE
Review jenkins jobs, and add to DSL if needed

### ISSUE THREAD

**Issue by mkjmdski** [vegaprotocol/jenkins-shared-library#209]
To make sure that we have proper retention and IaC control over jenkins we still need to migrate following jobs:

### To Migrate
  - [private - cd/infra] top up bots fairground - this is failing cos of bots, but it needs to be running
  - [common] approbation
  - [common] nightly full system test run
  - [common] nightly full system test run - network infra
### To Review
  - [private] Playgrounds subdirectory - this could be left outside of DSL - playgrounds don't work nicely with DSL, what is an alternative solution
### To estimate
  - [private] Pirvate Repositories - GitHub Organization pipeline
  - [home] vegacapsule - multibranch
  - [home] vegacore - multibranch
### Deleted
  * [deleted] backup subdirectory - seems all jobs can be deleted
  * [deleted] Private Network
  * [cleaned up] To remove - old pipelines are moved here, there are 3 pipelines that were moved 3 days ago - leave them for a couple of days before deleting
### Other
  * [don't touch] LNL-create-restore - old pipeline, should be replaced with a new one (based on capsule)
  * [don't touch] Mainnet-Checkpoint-Test-Run - old pipeline, should be replaced with a new one (based on capsule)

**Comment by mkjmdski** [comment]
Make sure that mentioned ticket is implemented in scope of this

**Comment by mkjmdski** [comment]
System tests and top up are migrated

**Comment by gordsport** [comment]
@mkjmdski - please can you confirm we can close this?

**Comment by mkjmdski** [comment]
Yes we can close this, thank you @gordsport
