### ISSUE TITLE
Prevent from running simultaneous jobs on one Vega Network

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/jenkins-shared-library#252]
We have multiple different pipelines that interact with one vega network. They do perform "breaking" changes and are not expecting anything else to interact with it at that time.

Please introduce global Jenkins locks for each network (e.g. `devnet1-network-lock` or a different name) and use it in all pipelines or just steps that are breaking. Or use an alternative solution that can achieve the goal.
The general expectation is that a pipeline waits for the lock, and once it is released, it resumes.

**Comment by mkjmdski** [comment]
we should use this plugin https://www.jenkins.io/doc/pipeline/steps/lockable-resources 

* scenario 1 (easier): restart of n01.devent2.vega.xyz locks "devnet2".  Restart of entire devnet2 also lock "devnet2". That way both jobs block each other from execution.

* scenario 2 (harder): restart of n01.devent2.vega.xyz locks "n01.devent2.vega.xyz". Restart of entire devnet2 locks n01.devent2.vega.xyz to n08.devent2.vega.xyz if 8 nodes. That scenario is needed if we want to trigger multiple restarts in parallel.

I opt for scenario 1.

Example implementation:

```jenkinsfile
pipeline { 
  options {
    lock(resource: params.NET_NAME)
  }
}
}
```

**Comment by fkondej** [comment]
I am also in favour of option 1.
I don't think we will need option 1, but if we do, we can switch at that time.
