### ISSUE TITLE
Fix Fairground Snapshot testing

### ISSUE THREAD

**Issue by mkjmdski** [vegaprotocol/jenkins-shared-library#271]
https://jenkins.ops.vega.xyz/job/private/job/Snapshots/job/Fairground/ -> this started failing. We have disabled it for now, probable issue is that paths of configs on the new testnet are different than old ones and require updating. It's also possible that a different approach might come in handy (like creating a new node as jenkins-agent, and running ansible `barenode` on localhost to check, after that execute some verification scripting).

**Comment by mkjmdski** [comment]
```
[Pipeline] }
12:54:44  Failed in branch genesis.json
12:54:44  scp: /home/vega/current/vega: No such file or directory
[Pipeline] }
[Pipeline] // withCredentials
```
failing line -> https://github.com/vegaprotocol/jenkins-shared-library/blob/main/vars/pipelineSnapshotTesting.groovy#L108

**Comment by mkjmdski** [comment]
example run -> https://jenkins.ops.vega.xyz/job/private/job/Snapshots/job/Fairground/3023/console

**Comment by gordsport** [comment]
for now:

- [ ] correct the path to the genesis file and vega core
- [ ] test by enabling on dev/stagnet 
- [ ] if OK discuss with ELT moving to testnet
