### ISSUE TITLE
Re-enable snapshot backup for Fairground

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/jenkins-shared-library#404]
I have disabled backing up snapshots for Fairground in #403 because that step has constantly been failing.
The [GitHub repo with snapshots](https://github.com/vegaprotocol/snapshot-backups) is too big, and it times out to clone.

We can either disable this step and relay on archiving artefacts in Jenkins or workaround the problem with slow cloning.

**Comment by gordsport** [comment]
Closing - will need new tickets for mainnet and validator testnet in the future
