### ISSUE TITLE
LNL Mainnet Chckpoint fixes

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/jenkins-shared-library#489]
1/ Any step failures should fail the pipeline run 

Thow exception for step failure on LNL mainnet pipeline

this pipeline
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-lnl-mainnet/detail/system-tests-lnl-mainnet/352/pipeline/546/

run system tests

This step failed but pipeline continued
I created a PR to capture the error
https://github.com/vegaprotocol/jenkins-shared-library/pull/488

2/ Allow override of the jenkins build

https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/352/parameters/

3/ Send pipeline results to slack channel to we are notified of a failure - can provide

4/ Switch back on the step to add a new data node from history segment

**Comment by daniel1302** [comment]
Ad 2. 

If you want to override Jenkins shared library(https://github.com/vegaprotocol/jenkins-shared-library), there is an option.

When you scroll down the page, there is a parameter called: `JENKINS_SHARED_LIB_BRANCH; Branch of jenkins-shared-library from which pipeline should be run`.
![image](https://github.com/vegaprotocol/jenkins-shared-library/assets/1239637/f7a7a861-a41a-46a7-a2f2-727e08dcba7d)

Then this params is hardcoded in the pipeline code header:
![image](https://github.com/vegaprotocol/jenkins-shared-library/assets/1239637/82fafab4-b68c-4566-8c04-36cfc60f1662)

**Comment by daniel1302** [comment]
Ad 3.
PR is here: https://github.com/vegaprotocol/jenkins-shared-library/pull/492
![image](https://github.com/vegaprotocol/jenkins-shared-library/assets/1239637/2f6e6439-275b-46ff-b2eb-8a70b68493fc)

**Comment by daniel1302** [comment]
Ad 1. and 4. Its more to do. I have some PRs ready but I am still testing it
