### ISSUE TITLE
Add a Jenkins pipeline for the perps mode system tets

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/jenkins-shared-library#723]
In order to complete the work started in the following system tests issue we need to add a CI pipeline for

- https://github.com/vegaprotocol/system-tests/pull/2779

Tasks:

- bring Sohill's Jenkins branch back to life and merge it in: https://github.com/vegaprotocol/jenkins-shared-library/compare/main...perps-run-system-test
- setup some recurring pipeline that will run it overnight once a week or whatever
- fix up any failing tests on the perp run as they appear

**Comment by daniel1302** [comment]
Needs some testing.
